//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMLCatalog.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/DMLService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDMLService")]
    public interface IDMLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMLService/GetData", ReplyAction="http://tempuri.org/IDMLService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMLService/GetData", ReplyAction="http://tempuri.org/IDMLService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMLService/CreateFolder", ReplyAction="http://tempuri.org/IDMLService/CreateFolderResponse")]
        string CreateFolder(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMLService/CreateFolder", ReplyAction="http://tempuri.org/IDMLService/CreateFolderResponse")]
        System.Threading.Tasks.Task<string> CreateFolderAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMLService/EditAccess", ReplyAction="http://tempuri.org/IDMLService/EditAccessResponse")]
        string EditAccess(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMLService/EditAccess", ReplyAction="http://tempuri.org/IDMLService/EditAccessResponse")]
        System.Threading.Tasks.Task<string> EditAccessAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMLService/Error", ReplyAction="http://tempuri.org/IDMLService/ErrorResponse")]
        void Error(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMLService/Error", ReplyAction="http://tempuri.org/IDMLService/ErrorResponse")]
        System.Threading.Tasks.Task ErrorAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMLService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDMLService/GetDataUsingDataContractResponse")]
        DMLCatalog.ServiceReference1.CompositeType GetDataUsingDataContract(DMLCatalog.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMLService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDMLService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<DMLCatalog.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(DMLCatalog.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDMLServiceChannel : DMLCatalog.ServiceReference1.IDMLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DMLServiceClient : System.ServiceModel.ClientBase<DMLCatalog.ServiceReference1.IDMLService>, DMLCatalog.ServiceReference1.IDMLService {
        
        public DMLServiceClient() {
        }
        
        public DMLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DMLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string CreateFolder(string value) {
            return base.Channel.CreateFolder(value);
        }
        
        public System.Threading.Tasks.Task<string> CreateFolderAsync(string value) {
            return base.Channel.CreateFolderAsync(value);
        }
        
        public string EditAccess(string value) {
            return base.Channel.EditAccess(value);
        }
        
        public System.Threading.Tasks.Task<string> EditAccessAsync(string value) {
            return base.Channel.EditAccessAsync(value);
        }
        
        public void Error(string value) {
            base.Channel.Error(value);
        }
        
        public System.Threading.Tasks.Task ErrorAsync(string value) {
            return base.Channel.ErrorAsync(value);
        }
        
        public DMLCatalog.ServiceReference1.CompositeType GetDataUsingDataContract(DMLCatalog.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<DMLCatalog.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(DMLCatalog.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
