//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMLCatalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmlcatalog
    {
        public int id { get; set; }
        public string name { get; set; }
        public string guid { get; set; }
        public string version { get; set; }
        public string description { get; set; }
        public int stateid { get; set; }
        public int typeid { get; set; }
        public Nullable<int> publisherid { get; set; }
        public Nullable<int> localizeid { get; set; }
        public string path { get; set; }
        public bool locked { get; set; }
    
        public virtual dmllocalize dmllocalize { get; set; }
        public virtual dmlpublisher dmlpublisher { get; set; }
        public virtual dmlstate dmlstate { get; set; }
        public virtual dmltype dmltype { get; set; }
    }
}
