//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMLCatalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmlhistory
    {
        public int id { get; set; }
        public int catalogid { get; set; }
        public System.DateTime datetime { get; set; }
        public string owner { get; set; }
        public string eventtext { get; set; }
        public string paramname { get; set; }
        public string paramold { get; set; }
        public string paramnew { get; set; }
    
        public virtual dmlcatalog dmlcatalog { get; set; }
    }
}
