//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMLCatalog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dmldbEntities : DbContext
    {
        public dmldbEntities()
            : base("name=dmldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dmlcatalog> dmlcatalog { get; set; }
        public virtual DbSet<dmlhistory> dmlhistory { get; set; }
        public virtual DbSet<dmllocalize> dmllocalize { get; set; }
        public virtual DbSet<dmlpublisher> dmlpublisher { get; set; }
        public virtual DbSet<dmlstate> dmlstate { get; set; }
        public virtual DbSet<dmltype> dmltype { get; set; }
    }
}
